### ISSUE TITLE
There is no truncate method to reset id counter

### ISSUE THREAD

**Issue by avcial** [objectbox/objectbox-examples#48] opened 2018-09-12 23:52 UTC
Is there a way to reset id counter for tables, like truncate in tsql.
box.removeAll not work for this.

**Comment by greenrobot-team** [comment] 2018-09-17 06:08
Closing as duplicate of https://github.com/objectbox/objectbox-java/issues/557

This issue tracker is used only for the examples.
-ut

**Closed by greenrobot-team** 2018-09-17 06:08 UTC
